---
- name: "Add SSH keys to host"
  hosts: all
  gather_facts: true

  vars:
    ansible_host_key_checking: false
    keys_repo: "/builds/ubuntu/key-deployment/autorized_keys"
    keys_origin: "/home/ubuntu/.ssh/authorized_keys"
    config_origin: "/etc/ssh/sshd_config"
    backup_date: >
      {{ ansible_date_time.date }}_{{ ansible_date_time.hour }}
      {{ ansible_date_time.minute }}{{ ansible_date_time.second }}

  tasks:
    - debug: var=ansible_host
    - name: Touch authorized_keys file if not present
      ansible.builtin.file:
        path: "{{ keys_origin }}"
        state: touch
        mode: "0600"
      become: true
      become_user: ubuntu

    - name: "Backup /home/ubuntu/.ssh/authorized_keys"
      ansible.builtin.copy:
        src: "{{ keys_origin }}"
        dest: "{{ keys_origin }}.backup_{{ backup_date }}"
        remote_src: true
        backup: true
        mode: "0600"
      become: true

    - name: Backup /etc/ssh/sshd_config
      ansible.builtin.copy:
        src: "{{ config_origin }}"
        dest: "{{ config_origin }}.backup_{{ backup_date }}"
        remote_src: true
        backup: true
        mode: "0644"
      become: true

    - name: "Add SSH keys if not present in file"
      ansible.posix.authorized_key:
        user: ubuntu
        key: "{{ item }}"
        state: present
        manage_dir: true
      with_items: "{{ lookup('file', keys_repo).split('\n') }}"
      when: lookup('file', keys_repo, errors='ignore') != ""
      become: true

    - name: "Modify /etc/ssh/sshd_config"
      ansible.builtin.lineinfile:
        path: "{{ config_origin }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: '^#?\s*PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'
        - regexp: '^#?\s*PasswordAuthentication'
          line: 'PasswordAuthentication yes'
      notify: restart sshd
      become: true

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true

    - name: Remove backup
      ansible.builtin.file:
        path: "{{ config_origin }}.backup_{{ backup_date }}"
        state: absent
      become: true
